/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Coder Wen",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "styles/index.styl"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/student/",
      "relativePath": "student/README.md",
      "key": "v-4dc4e152",
      "path": "/student/"
    },
    {
      "title": "河南科技大学",
      "frontmatter": {
        "title": "河南科技大学"
      },
      "regularPath": "/student/keda/",
      "relativePath": "student/keda/README.md",
      "key": "v-4810826d",
      "path": "/student/keda/",
      "headers": [
        {
          "level": 2,
          "title": "软件学院",
          "slug": "软件学院"
        },
        {
          "level": 2,
          "title": "应用工程学院",
          "slug": "应用工程学院"
        },
        {
          "level": 3,
          "title": "魏耀鹏",
          "slug": "魏耀鹏"
        },
        {
          "level": 3,
          "title": "于水长",
          "slug": "于水长"
        },
        {
          "level": 3,
          "title": "刘佳文",
          "slug": "刘佳文"
        },
        {
          "level": 3,
          "title": "陈艳杰",
          "slug": "陈艳杰"
        },
        {
          "level": 3,
          "title": "何青云",
          "slug": "何青云"
        },
        {
          "level": 3,
          "title": "于思佳",
          "slug": "于思佳"
        },
        {
          "level": 3,
          "title": "刘佳伟",
          "slug": "刘佳伟"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": null,
        "heroText": "Hi,朋友",
        "tagline": "这是一个用户学习交流开发知识的个人博客，希望你能在这里找到对你有用的东西。",
        "actionText": "人才库",
        "subSidebar": false,
        "actionLink": "/student/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-15c89286",
      "path": "/"
    },
    {
      "title": "ASP.NET MVC框架",
      "frontmatter": {
        "title": "ASP.NET MVC框架"
      },
      "regularPath": "/csharp/mvc.html",
      "relativePath": "csharp/mvc.md",
      "key": "v-eeca291a",
      "path": "/csharp/mvc.html",
      "headers": [
        {
          "level": 2,
          "title": "ORM对象关系映射",
          "slug": "orm对象关系映射"
        },
        {
          "level": 2,
          "title": "EF的创建",
          "slug": "ef的创建"
        },
        {
          "level": 2,
          "title": "IEnumerable、IQueryable、List三种数据结构",
          "slug": "ienumerable、iqueryable、list三种数据结构"
        },
        {
          "level": 2,
          "title": "ASP.NET MVC框架",
          "slug": "asp-net-mvc框架"
        },
        {
          "level": 2,
          "title": "Razor",
          "slug": "razor"
        },
        {
          "level": 3,
          "title": "MVC中编写联合语句",
          "slug": "mvc中编写联合语句"
        },
        {
          "level": 2,
          "title": "前后端分离开发模式",
          "slug": "前后端分离开发模式"
        },
        {
          "level": 2,
          "title": "EF的常用方法",
          "slug": "ef的常用方法"
        },
        {
          "level": 2,
          "title": "ViewData和ViewBag",
          "slug": "viewdata和viewbag"
        },
        {
          "level": 2,
          "title": "Action四种返回类型",
          "slug": "action四种返回类型"
        },
        {
          "level": 2,
          "title": "区域Area",
          "slug": "区域area"
        },
        {
          "level": 2,
          "title": "Filter拦截器（过滤器）",
          "slug": "filter拦截器-过滤器"
        },
        {
          "level": 3,
          "title": "概念",
          "slug": "概念"
        },
        {
          "level": 3,
          "title": "过滤器的类型与作用",
          "slug": "过滤器的类型与作用"
        },
        {
          "level": 3,
          "title": "ActionFilterAttribute",
          "slug": "actionfilterattribute"
        },
        {
          "level": 3,
          "title": "ResultFilter",
          "slug": "resultfilter"
        },
        {
          "level": 3,
          "title": "AuthorizeAttribute",
          "slug": "authorizeattribute"
        },
        {
          "level": 3,
          "title": "HandleErrorAttribute",
          "slug": "handleerrorattribute"
        },
        {
          "level": 2,
          "title": "路由",
          "slug": "路由"
        },
        {
          "level": 2,
          "title": "模型注解",
          "slug": "模型注解"
        },
        {
          "level": 3,
          "title": "什么是验证，数据注解",
          "slug": "什么是验证-数据注解"
        },
        {
          "level": 3,
          "title": "验证注解的使用",
          "slug": "验证注解的使用"
        },
        {
          "level": 3,
          "title": "注解的验证",
          "slug": "注解的验证"
        },
        {
          "level": 3,
          "title": "显示和编辑注解",
          "slug": "显示和编辑注解"
        },
        {
          "level": 3,
          "title": "自定义验证逻辑",
          "slug": "自定义验证逻辑"
        }
      ]
    },
    {
      "title": "ASP.NET Core MVC",
      "frontmatter": {
        "title": "ASP.NET Core MVC",
        "sidebar": "auto"
      },
      "regularPath": "/csharp/core.html",
      "relativePath": "csharp/core.md",
      "key": "v-849e79ea",
      "path": "/csharp/core.html",
      "headers": [
        {
          "level": 2,
          "title": "简介",
          "slug": "简介"
        },
        {
          "level": 2,
          "title": "项目结构",
          "slug": "项目结构"
        },
        {
          "level": 2,
          "title": "中间件(Middleware)",
          "slug": "中间件-middleware"
        },
        {
          "level": 2,
          "title": "常用中间件",
          "slug": "常用中间件"
        },
        {
          "level": 2,
          "title": "加载静态资源",
          "slug": "加载静态资源"
        },
        {
          "level": 2,
          "title": "设置初始页",
          "slug": "设置初始页"
        },
        {
          "level": 2,
          "title": "再聊MVC",
          "slug": "再聊mvc"
        },
        {
          "level": 2,
          "title": "ASP.NET Core MVC使用",
          "slug": "asp-net-core-mvc使用"
        },
        {
          "level": 2,
          "title": "ViewStart和ViewImport",
          "slug": "viewstart和viewimport"
        },
        {
          "level": 2,
          "title": "LibMan使用",
          "slug": "libman使用"
        },
        {
          "level": 2,
          "title": "ASP.NET Core自带的IOC容器",
          "slug": "asp-net-core自带的ioc容器"
        },
        {
          "level": 2,
          "title": "TagHelper",
          "slug": "taghelper"
        },
        {
          "level": 2,
          "title": "使用ORM",
          "slug": "使用orm"
        },
        {
          "level": 2,
          "title": "数据迁移",
          "slug": "数据迁移"
        },
        {
          "level": 2,
          "title": "种子数据",
          "slug": "种子数据"
        },
        {
          "level": 2,
          "title": "Session",
          "slug": "session"
        },
        {
          "level": 2,
          "title": "日志记录nlog",
          "slug": "日志记录nlog"
        },
        {
          "level": 2,
          "title": "Filter拦截器",
          "slug": "filter拦截器"
        },
        {
          "level": 2,
          "title": "Authonization Filter",
          "slug": "authonization-filter"
        }
      ]
    },
    {
      "title": "洛阳职业技术学院",
      "frontmatter": {
        "title": "洛阳职业技术学院"
      },
      "regularPath": "/student/luozhi/",
      "relativePath": "student/luozhi/README.md",
      "key": "v-83545c26",
      "path": "/student/luozhi/"
    },
    {
      "title": "Vue",
      "frontmatter": {
        "title": "Vue"
      },
      "regularPath": "/webfront/vue.html",
      "relativePath": "webfront/vue.md",
      "key": "v-c00e8e02",
      "path": "/webfront/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "为什么学习vue.js",
          "slug": "为什么学习vue-js"
        },
        {
          "level": 2,
          "title": "简单认识一个vuejs",
          "slug": "简单认识一个vuejs"
        },
        {
          "level": 2,
          "title": "vuejs安装方式",
          "slug": "vuejs安装方式"
        },
        {
          "level": 2,
          "title": "vuejs初体验",
          "slug": "vuejs初体验"
        },
        {
          "level": 2,
          "title": "vue实例传入的options",
          "slug": "vue实例传入的options"
        },
        {
          "level": 2,
          "title": "MVVM",
          "slug": "mvvm"
        },
        {
          "level": 2,
          "title": "什么是MVVM Model  View ViewModel",
          "slug": "什么是mvvm-model-view-viewmodel"
        },
        {
          "level": 3,
          "title": "View层",
          "slug": "view层"
        },
        {
          "level": 3,
          "title": "Model",
          "slug": "model"
        },
        {
          "level": 3,
          "title": "ViewModel",
          "slug": "viewmodel"
        },
        {
          "level": 2,
          "title": "Vue的生命周期",
          "slug": "vue的生命周期"
        },
        {
          "level": 2,
          "title": "指令",
          "slug": "指令"
        },
        {
          "level": 3,
          "title": "参数",
          "slug": "参数"
        },
        {
          "level": 3,
          "title": "动态参数",
          "slug": "动态参数"
        },
        {
          "level": 3,
          "title": "修饰符",
          "slug": "修饰符"
        },
        {
          "level": 3,
          "title": "缩写",
          "slug": "缩写"
        },
        {
          "level": 2,
          "title": "bind指令",
          "slug": "bind指令"
        },
        {
          "level": 3,
          "title": "计算属性",
          "slug": "计算属性"
        },
        {
          "level": 3,
          "title": "侦听器watch",
          "slug": "侦听器watch"
        },
        {
          "level": 3,
          "title": "计算属性的setter和getter",
          "slug": "计算属性的setter和getter"
        },
        {
          "level": 2,
          "title": "事件监听",
          "slug": "事件监听"
        },
        {
          "level": 2,
          "title": "条件判断",
          "slug": "条件判断"
        },
        {
          "level": 2,
          "title": "v-for指令",
          "slug": "v-for指令"
        },
        {
          "level": 3,
          "title": "组件的key属性",
          "slug": "组件的key属性"
        },
        {
          "level": 3,
          "title": "ES6for of和for in",
          "slug": "es6for-of和for-in"
        },
        {
          "level": 2,
          "title": "过滤器Filter",
          "slug": "过滤器filter"
        },
        {
          "level": 2,
          "title": "v-model基础用法",
          "slug": "v-model基础用法"
        },
        {
          "level": 3,
          "title": "文本",
          "slug": "文本"
        },
        {
          "level": 3,
          "title": "多行文本",
          "slug": "多行文本"
        },
        {
          "level": 3,
          "title": "复选框",
          "slug": "复选框"
        },
        {
          "level": 3,
          "title": "单选按钮",
          "slug": "单选按钮"
        },
        {
          "level": 3,
          "title": "选择框",
          "slug": "选择框"
        },
        {
          "level": 3,
          "title": "值绑定",
          "slug": "值绑定"
        },
        {
          "level": 3,
          "title": "复选框",
          "slug": "复选框-2"
        },
        {
          "level": 3,
          "title": "单选按钮",
          "slug": "单选按钮-2"
        },
        {
          "level": 3,
          "title": "选择框的选项",
          "slug": "选择框的选项"
        },
        {
          "level": 3,
          "title": "修饰符",
          "slug": "修饰符-2"
        },
        {
          "level": 3,
          "title": ".lazy",
          "slug": "lazy"
        },
        {
          "level": 3,
          "title": ".number",
          "slug": "number"
        },
        {
          "level": 3,
          "title": ".trim",
          "slug": "trim"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "noFoundPageByTencent": false,
    "type": "blog",
    "authorAvatar": "/lg.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端",
        "link": "",
        "items": [
          {
            "text": "HTML5",
            "link": "/webfront/html"
          },
          {
            "text": "CSS3",
            "link": "/webfront/css"
          },
          {
            "text": "JavaScript",
            "link": "/webfront/js"
          },
          {
            "text": "Vue",
            "link": "/webfront/vue"
          }
        ]
      },
      {
        "text": ".NET",
        "link": "",
        "items": [
          {
            "text": "C#基础",
            "link": "/csharp/cshape/"
          },
          {
            "text": "ASP.NET MVC",
            "link": "/csharp/mvc/"
          },
          {
            "text": "ASP.NET Core MVC",
            "link": "/csharp/core/"
          }
        ]
      },
      {
        "text": "人才库",
        "link": "#",
        "items": [
          {
            "text": "河南科技大学",
            "link": "/student/keda/"
          },
          {
            "text": "洛阳职业技术学院",
            "link": "/student/luozhi/"
          }
        ]
      },
      {
        "text": "面试",
        "link": ""
      }
    ],
    "subSidebar": "auto",
    "friendLink": [
      {
        "title": "康辉软件",
        "desc": "一家专业从事计算机软件人才培训的机构，始终坚持诚信至上，学员为本，质量第一的原则，以关心学生，和谐发展的管理理念，打造一流的师资培训队伍，完善的教学设施，真是事项高薪就业的宗旨。",
        "link": "http://www.kanghuisw.com/",
        "logo": "http://www.kanghuisw.com/Content/images/logo.png"
      },
      {
        "title": "vuepress-theme-reco",
        "desc": "一个机遇vuepress简洁、漂亮的博客主题",
        "logo": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      },
      {
        "title": "Vue",
        "desc": "一套用于构建用户界面的渐进式框架",
        "link": "https://cn.vuejs.org/",
        "logo": "https://cn.vuejs.org/images/logo.svg"
      }
    ]
  }
}